### ISSUE TITLE
SLURM logging & some questions

### ISSUE THREAD

**Issue by lucasdekam** [jla-gardner/graph-pes#91]
Hi there,
First of all I really like this work, it nicely relates different models to each other by building them up in a modular way with Python objects. Also appreciate the documentation effort. As the code matures I can definitely see myself using this code more. I ran into some issues though. While not urgent, I would be interested if you could take a look at it.

**Logging on HPC**
I played around with the MACE implementation on a HPC, and I struggled a bit with setting up logging. The progress bar does not display in a SLURM log, and the logging file at `graph-pes-results/modelname/logs/rank-0.log` only displays the loss, not force RMSE et cetera. Is there a way to enable more informative logging, like in the ACEsuit/mace package? 

**Comparison to reference MACE**
Setting up MACE with 
```
model:
  core-repulsion:
    +ZBLCoreRepulsion:
      cutoff: 5
      trainable: true
  many-body:
    +MACE:
      channels: 128
      cutoff: 5
      elements:
      - H
      - O
      - Pt
      hidden_irreps: 0e + 1o
      self_connection: true
``` 
it says the model has around 600k parameters, but with the ACEsuit/MACE I get around 750k parameters. I used the following settings there, otherwise default:
```
  --r_max=5.0 \\
  --num_interactions=2 \\
  --hidden_irreps="128x0e + 128x1o" \\
```
Is there some implementation difference or are there different defaults?

ACEsuit/MACE ran out of memory on an A100 GPU when using large structures, whereas graph-pes doesn't, which is cool. Maybe it's due to the optimized einsum used, or maybe just due to less parameters (?).

It would be really cool if it was possible to load ACEsuit/MACE models into `graph-pes` to make use of all the nice analysis and exploration tools, but this is probably not easy to do due to slight implementation differences, right? 

**Gradient clipping** 
When I used the same learning rate as in ACEsuit/MACE (`1e-2`), I got NaNs in the loss. With lr `3e-3` it did work (although I think training converged more slowly than for ACEsuit/MACE, maybe due to lower LR or other suboptimal settings). Could it be that there's no gradient clipping (yet) in `graph-pes`? 

Thanks and keep up the good work!

**Comment by jla-gardner** [comment]
Hi there @lucasdekam!

First of all, thanks for giving `graph-pes` a try! I'm glad that its starting to get some use 😄 

In answer to your queries:

## Logging on HPC

By default, `graph-pes` relies on the [RichProgressBar](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.RichProgressBar.html) from PyTorch Lightning. Unfortunately this doesn't render nicely in logs. To fix this, please try the following config addition:

```yaml
general:
   progress: logged
```

This will print out validation energy/force rmse at the end of every epoch in a similar manner to ACEsuite/MACE. 

If you have a [Weights & Biases](https://wandb.ai/home) account, then your online logs will update in real time, and in an interactive manner, while your SLURM job runs!

## Comparison to reference MACE

I shall look into this now! When implementing the `graph_pes.models.MACE` class, I tried to stick as closely as possible to the original pre-print. This may have since diverged from the implementation available in ACEsuite. I would expect there to be some small difference due to the way that `graph-pes` handles parameters that are "per-atom" (see [the docs](https://jla-gardner.github.io/graph-pes/building-blocks/nn.html#graph_pes.utils.nn.PerElementParameter)), but a difference of this size is probably due to a difference in defaults. 

I shall keep you updated on this!

As for porting ACEsuite models over to graph-pes, you're right - loading model weights over into the graph-pes implementation is not going to be possible at the moment - this may be possible in the future (stay tuned 😃)

## Gradient clipping

I shall implement gradient clipping today! Again, I'll let you know when this is ready

**Comment by lucasdekam** [comment]
Hi, thanks! The gradient clipping works! (I put `trainer_kwargs` rather than `trainer` in the config, or does both work?)

Somehow when putting `progress: logged` I still don't get any logged progress in my SLURM output. Maybe the printing is not being flushed? Or any other suggestions if I'm doing something wrong? 

Relevant parts of my config:
```
general:
    seed: 0
    run_id: mace
    progress: logged

fitting:
    trainer_kwargs:
        max_epochs: 5
        accelerator: gpu
        check_val_every_n_epoch: 1
        log_every_n_steps: 1
        gradient_clip_val: 10.0
        gradient_clip_algorithm: "norm"
```

And then the SLURM output seems to get stuck here:

```
Number of learnable params:
    offset (FixedOffset)             : 0
    core-repulsion (ZBLCoreRepulsion): 2
    many-body (MACE)                 : 604,043

[graph-pes INFO]: Sanity checking the model...
[graph-pes INFO]: Starting fit...
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/ldkam/miniconda3/envs/cueq/lib/python3.10/site-packages/torch/_compile.py:32: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  return disable_fn(*args, **kwargs)
SLURM auto-requeueing enabled. Setting signal handlers.
``` 

The `rank-0.log` file looks like this:
```
[graph-pes INFO]: Starting fit...
[graph-pes DEBUG]:
Using LR scheduler config:
{'interval': 'epoch', 'frequency': 1, 'monitor': 'valid/loss/total', 'strict': True}

[graph-pes DEBUG]: New best model: validation loss 93.93170166015625
[graph-pes DEBUG]: Model saved to graph-pes-results/mace/model.pt
[graph-pes DEBUG]: Deployed model for use with LAMMPS to graph-pes-results/mace/lammps_model.pt
[graph-pes DEBUG]: New best model: validation loss 1.4949076175689697
[graph-pes DEBUG]: Model saved to graph-pes-results/mace/model.pt
[graph-pes DEBUG]: Deployed model for use with LAMMPS to graph-pes-results/mace/lammps_model.pt
```

**Comment by jla-gardner** [comment]
I'm glad the gradient clipping worked 🥳 you're right, `trainer_kwargs` is the place to put that.

As for the `MACE` parameter discrepancies, I have now aligned the graph-pes implementation to exactly match the ACEsuite/mace one (see #93) Thanks for pointing this out! I had been putting a residual connection in the wrong place. I now get ~750k params using the above config. This has been included in version `0.0.14`: to install that please run `pip install --upgrade graph-pes`.

As for the log flushing, I have also attempted to fix that in `0.0.14`. If that still fails to work, perhaps you could try:
```bash
export PYTHONUNBUFFERED=1
graph-pes-train ...
```
This should force python to flush the print statements for logging to your SLURM output file 🤞 

---

One final comment: are you training on formation energies? Or do your structures have an (arbitrary) energy offset - i.e. would the energy label of a single H, O and Pt atom be 0 or not? If not, you can learn this offset using the following configuration:

```yaml
model:
  offset: +LearnableOffset()
  core-repulsion:
    +ZBLCoreRepulsion:
      cutoff: 5
      trainable: true
  many-body:
    +MACE:
      channels: 128
      cutoff: 5
      elements: [H, O, Pt]
      hidden_irreps: 0e + 1o
      self_connection: true
```

(see the [docs](https://jla-gardner.github.io/graph-pes/models/many-body/mace.html#scaleshiftmace) for more details)

**Comment by lucasdekam** [comment]
Cool, I'll test the logging and MACE architecture. 

I didn't post that part of my config before but I'm using a fixed offset based on single-atom DFT calculations:
```    
offset:
+FixedOffset: {"H": -13.575675192725026, "O": -430.9174941273589, "Pt": -709.2447124246002}
```
Thanks for the heads-up anyways!

Two more points that came up:

* After updating to the latest version, I get an error when `graph-pes` is loading an `AtomGraph` object from a pickle. I'm not sure where these pickles are stored. Maybe it'd be good to log this location, and/or create a new one if the pickle cannot be loaded?

```
ESC[30m[graph-pes INFO]: Preparing dataESC[0m
ESC[31m[graph-pes ERROR]: Training failed: AtomicGraph.__new__() missing 1 required positional argument: 'other'ESC[0m
Traceback (most recent call last):

...

  File "/home/ldkam/miniconda3/envs/graph-pes/lib/python3.10/site-packages/locache.py", line 109, in wrapper
    result = pickle.load(file)
TypeError: AtomicGraph.__new__() missing 1 required positional argument: 'other'
```

(not sure what this ESC[... is before the logging, maybe related to the logging update?) 

* Yesterday I learned about [cuEquivariance](https://docs.nvidia.com/cuda/cuequivariance/index.html); acesuit/MACE now has an implementation that uses this and I got quite a decent speed-up from that in training (~3x). If I understand correctly it's kind of an alternative to e3nn. It could be something to consider for the future :-) 

Feel free to look at it later, it's not urgent, just hoping to help the development!

**Comment by jla-gardner** [comment]
Hey @lucasdekam - sorry about the pickling errors - I upgraded the `AtomGraph` base class in `0.0.14`, meaning previously cached files were out of date. In `0.0.16`, I've fixed this (both logging where things are pickled, and also re-calculating them if the pickled version is out of date and fails 😄)

Yes the `ESC[...` is part of a logging bug that is also fixed in `0.0.16` - again, you can pull these changes via `pip install --upgrade graph-pes` - I hope this now fixes your issues!


As for [cuEquivariance](https://docs.nvidia.com/cuda/cuequivariance/index.html), I have been aware of this for a few days already - I'll be trying to incorporate this into `graph-pes` soon for even faster training!

Thank you again for trying `garph-pes` out and for reporting these errors! Its incredibly useful to have someone trying this on a completely new and different compute system to those we've tested it on.

**Comment by lucasdekam** [comment]
Sorry for radio silence, I'll get back to exploring more soon :-) also the MACEWrapper looks promising, that way I can try the features with models I already trained!
